### ISSUE TITLE
bootstrap.cfg configuration missing form nREPL service documentation

### ISSUE THREAD

**Issue by jsyrjala** [puppetlabs/trapperkeeper#178]
nREPL service documentation in https://github.com/puppetlabs/trapperkeeper/wiki/Built-in-nREPL-Service should contain a section what to add to `bootstrap.cfg' to enable the nRepl service.

Wiki talks about three built in services: configuration service, shutdown service and nREPL service. First two are built in and enabled by default, the last is built in but disabled by default.

You need to add `puppetlabs.trapperkeeper.services.nrepl.nrepl-service/nrepl-service` to bootstrap.cfg to enable the nREPL service.

**Comment by cprice404** [comment]
@nathanielksmith I am doing a random drive-by of old open issues on the TK repo; did we ever do this?

**Comment by nathanielksmith** [comment]
@cprice404 totally don't remember self assigning this. it looks like the action item here is to add something to the nrepl service's documentation page to talk about adding the above to bootstrap.cfg and i don't see that, so no, we didn't do this. i can take care of it today.

**Comment by nathanielksmith** [comment]
Fixed in #236
