### ISSUE TITLE
Support for updated schema and plumbing deps

### ISSUE THREAD

**Issue by dparis** [puppetlabs/trapperkeeper#187]
My trapperkeeper project requires plumbing/schema versions 0.4.x and I'm running into a number of incompatibility errors. I've started fixing them (fixed `trapperkeeper-webserver-jetty9`, working on `puppetlabs/http-client`) and I'm not sure how deep the rabbit hole goes.

I'd be happy to contribute my fixes if you haven't already started doing this internally. If the fixes need to be coordinated across several repos, though, I might need some guidance for how you'd prefer them to be submitted. I've read the contrib guidelines and set up a JIRA account, just let me know if/how you'd like me to proceed.

**Comment by dparis** [comment]
The rabbit hole turned out to be quite shallow. :smile: 

Only needed to update those two projects to get everything working with the latest version of `prismatic/schema` and `prismatic/plumbing`. The changes were relatively minor, and all tests pass with the changes applied.

I'll create a couple new JIRA issues and make sure my commits are properly formatted. If there's anything else you'd like to see done, let me know.

**Comment by dparis** [comment]
PRs submitted to resolve this issue:

* https://github.com/puppetlabs/clj-http-client/pull/39
* https://github.com/puppetlabs/trapperkeeper-webserver-jetty9/pull/116
* https://github.com/puppetlabs/trapperkeeper/pull/188

**Comment by rlinehan** [comment]
@dparis Glad to hear the rabbit hole was not very deep! Thanks for doing all this work (and being so thorough about following the contributing guide), and making JIRA issues, we really appreciate it. We've been meaning to have a discussion about bumping these versions, so thank you for jump starting that. :) 

It might take us a week or so to get back to you about these changes as we have a weekly meeting to discuss new tickets on Wednesdays. We'll keep the JIRA ticket updated with our discussion.

**Comment by dparis** [comment]
@rlinehan No problem! I'll be traveling next week, but I'll try to keep an eye on the PRs and JIRA. Let me know if there's anything I can help with.

Also, hope to see you all at Clojure/West this year!
