### ISSUE TITLE
How to get a dependency service without starting a service?

### ISSUE THREAD

**Issue by timur87** [puppetlabs/trapperkeeper#194]
Hi,

Is there a way to get the instance of a dependency service without starting the service? I want to test certain functions using a dependency service but without actually starting the dependent service. 

Regards,

Timur

**Comment by cprice404** [comment]
@timur87 if I'm understanding you correctly, the best way to do this for testing is implement a mock version of the dependency service.  Then you can use the testutils `with-app-with-config` macro and pass it a list of services that you want it to include, including the mock version of the dependency service instead of the real version.

Would that suffice for your needs?

**Comment by timur87** [comment]
@cprice404, thanks for the prompt answer again. 

What I'm asking might be a really basic question :) What I need is an actual instance of the  dependency service. Something similar to (services/get-service this :MyProtocol) except without "this" parameter here so that I can call it outside of the start or init functions.

**Comment by cprice404** [comment]
@timur87 so this is in test code?  With a TK app booted up?  Or are you saying you're trying to write tests that test the service without booting a TK app?

If the latter, I would say that how we usually handle that is to

**Comment by timur87** [comment]
It's not a test code, I'm working in repl interactively and want to see if the service really do its job. It's a persistency service, and I want to see if the things are really added. For that I need to get an instance of a dependency service, i.e., persistency service. All of this is happening in CIDER nREPL :)

**Comment by cprice404** [comment]
Ah, OK, so you do have a full instance of the TK app running then.  There's probably a hacky way to do it; you can use this variable:

https://github.com/puppetlabs/trapperkeeper/blob/master/src/puppetlabs/trapperkeeper/core.clj#L122

to get a reference to the `TrapperkeeperApp` itself, and then use the `get-service` function from the `TrapperkeeperApp` protocol to get a reference to a service.

I hate having that global variable in the code but this is what I put it in there for, as a last resort for this kind of situation.  For a dev environment it'd probably be preferable to boot the tk-app explicitly in the repl and hold on to your own variable with a reference to the app, and access it through that, if possible.

**Comment by cprice404** [comment]
@timur87 did that work for your use case?

**Comment by timur87** [comment]
Yes it did thanks for the prompt answers as always!
