### ISSUE TITLE
Packaging application for production

### ISSUE THREAD

**Issue by timur87** [puppetlabs/trapperkeeper#197]
Hi all,

What is the standard workflow for packinging application for production? lein uberjar and then running the uberjar with java -jar? 

Regards,

Timur

**Comment by cprice404** [comment]
That is how we ship our apps, yes.

We actually have some internal tooling that will build RPMs and other operating system packages from the uberjar, but it may or may not be easy to set up outside of our Jenkins environment :)

https://github.com/puppetlabs/ezbake

**Comment by timur87** [comment]
Okay thanks!
